title: Teh Yoong Sin
logo: "assets/me.jpeg"
description: Chemical Engineer graduate, pursuing MSc in Data Science
email: tehyoongsin.ce@gmail.com
github_username: ether-silicon
theme: jekyll-theme-minimal
