title: Teh Yoong Sin
logo: "assests/Teh Yoong Sin.jpeg"
description: Chemical Engineer graduate, pursuing MSc in Data Science
email: tehyoongsin.ce@gmail.com
github_username: ether-silicon
theme: jekyll-theme-minimal
quotes: The best time to plant a tree was 20 years ago. The second best time is now. - Japanese proverb
startdate: September 2024
